### ISSUE TITLE
TK60 - Modificar DB para Poner Imagen de Avatar por Defecto

### ISSUE THREAD

**Issue by Uriel-98** [Nervios-de-Acero/Avocado-Android#21]
Modificar la base de datos para asignar una imagen de avatar por defecto a los nuevos usuarios al registrarse.

Criterios de Aceptación
Actualizar la estructura de la base de datos para incluir una imagen de avatar por defecto.
Asegurarse de que todos los nuevos registros de usuario tengan esta imagen por defecto si no se proporciona una propia.
Comentar adecuadamente los cambios realizados en la base de datos para futuras referencias.

Caso de Uso: Imagen de Avatar por Defecto
Dado que los nuevos usuarios deben tener una imagen de avatar por defecto,
Cuando se registre un nuevo usuario sin una imagen personalizada,
Entonces se asignará automáticamente una imagen de avatar de placeholder en la base de datos.

**Comment by Loreaylen** [comment]
Resuelto aquí https://github.com/Nervios-de-Acero/tesis-avocado/pull/93
